baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'PaperMod'

[params]
  author = 'Weijian'
  description = 'Personal blog and portfolio'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
